# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rtf}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Wood"]
  s.date = %q{2010-03-23}
  s.description = %q{Ruby RTF is a library that can be used to create rich text format (RTF) documents. RTF is a text based standard for laying out document content.}
  s.email = %q{paw220470@yahoo.ie}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION.yml",
     "examples/example01.rb",
     "examples/example02.rb",
     "examples/example03.rb",
     "examples/example03.rtf",
     "examples/example04.rb",
     "examples/rubyrtf.bmp",
     "examples/rubyrtf.jpg",
     "examples/rubyrtf.png",
     "lib/rtf.rb",
     "lib/rtf/colour.rb",
     "lib/rtf/font.rb",
     "lib/rtf/information.rb",
     "lib/rtf/node.rb",
     "lib/rtf/paper.rb",
     "lib/rtf/style.rb",
     "ruby-rtf.gemspec",
     "test/character_style_test.rb",
     "test/colour_table_test.rb",
     "test/colour_test.rb",
     "test/command_node_test.rb",
     "test/container_node_test.rb",
     "test/document_style_test.rb",
     "test/document_test.rb",
     "test/fixtures/bitmap1.bmp",
     "test/fixtures/bitmap2.bmp",
     "test/fixtures/jpeg1.jpg",
     "test/fixtures/jpeg2.jpg",
     "test/fixtures/png1.png",
     "test/fixtures/png2.png",
     "test/font_table_test.rb",
     "test/font_test.rb",
     "test/footer_node_test.rb",
     "test/header_node_test.rb",
     "test/image_node_test.rb",
     "test/information_test.rb",
     "test/node_test.rb",
     "test/paragraph_style_test.rb",
     "test/style_test.rb",
     "test/table_cell_node_test.rb",
     "test/table_node_test.rb",
     "test/table_row_node_test.rb",
     "test/test_helper.rb",
     "test/text_node_test.rb"
  ]
  s.homepage = %q{http://github.com/thechrisoshow/ruby-rtf}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby library to create rich text format documents.}
  s.test_files = [
    "test/node_test.rb",
     "test/information_test.rb",
     "test/container_node_test.rb",
     "test/table_cell_node_test.rb",
     "test/character_style_test.rb",
     "test/paragraph_style_test.rb",
     "test/font_test.rb",
     "test/document_test.rb",
     "test/style_test.rb",
     "test/font_table_test.rb",
     "test/text_node_test.rb",
     "test/table_node_test.rb",
     "test/colour_table_test.rb",
     "test/image_node_test.rb",
     "test/document_style_test.rb",
     "test/test_helper.rb",
     "test/footer_node_test.rb",
     "test/table_row_node_test.rb",
     "test/colour_test.rb",
     "test/header_node_test.rb",
     "test/command_node_test.rb",
     "examples/example01.rb",
     "examples/example02.rb",
     "examples/example03.rb",
     "examples/example04.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
